module.exports = {
  addMappings: require("./addMappings"),
  addStyleSheet: require("./addStyleSheet"),
  asChars: require("./asChars"),	
  asGlyphIDs: require("./asGlyphIDs"),	
  asHex: require("./asHex"),	
  asNumbers: require("./asNumbers"),	
  atou: require("./atou"),	
  buildTables: require("./buildTables"),
  convertOutline: require("./convertOutline"),
  dataBuilding: require("./dataBuilding"),
  getColor: require("./getColor"),
  makeStructy: require("./makeStructy"),
  Mapper: require("./Mapper"),
  nodeBuilder: require("./nodeBuilder"),
  shimFname: require("./shimFname"),
  struct: require("./struct"),
  toWOFF: require("./toWOFF"),
  toDataURL: require("./toDataURL")
};
